# Generated by Django 4.2.9 on 2025-12-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.CharField(default='CLP', max_length=3),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
